### ISSUE TITLE
npm version (3.1.9) is broken

### ISSUE THREAD

**Issue by karelbilek** [litecoin-project/litecore-node#1]
3.1.9 (the version of litecore-node on npm) is broken.

In `lib/services/bitcoind.js` it calls `require('bitcoind-rpc')`, but in `package.json` there is `litecoind-rpc` dependency. Replacing `bitcoind-rpc` with `litecoind-rpc` fixes the problem.

(I cannot correct it on github, since you have an old version here)

**Comment by slush0** [comment]
Please fix this soon. It blocks running Litecore from NPM until manually fixed in sources after installation. @losh11

**Comment by karelbilek** [comment]
Looks fixed on npm, but still not pushed here on github :)

**Comment by losh11** [comment]
Fixed in c09bb2534e27287eb695e2c45001193eb2849eab. I'll be cleaning up all repos shortly.
