### ISSUE TITLE
Bitcore-wallet-service error

### ISSUE THREAD

**Issue by g666nz** [litecoin-project/litecore-node#4]
Everytime i load up the BWS with insight api, i get an error  saying bitcore.lib copy and to remove extra's from sub modules and when i delete it, it says bitcore.lib not found. Anyone that can help me here.

I'm running it on ubuntu 16.04, ran the program without sudo privileges and downloaded all the pre requisites.

**Comment by losh11** [comment]
Bitcore-Wallet-Service needs to be forked to support Litecoin. Looks like most Bitcore-lib references have to be updated. I can do that if there's interest...

**Comment by g666nz** [comment]
We're looking into opening a litecoin exchange here in India. If there's an alternative i'm more than happy to use that. As long as it's based in node.js

**Comment by g666nz** [comment]
And the sooner the better. We've got our bitcoin and ethereum node's running, been struggling with this for the past 4 hours.

**Comment by losh11** [comment]
Okay, I'll try to get this done for you later.

**Comment by g666nz** [comment]
Thank you so much. Appreciate it alot.

**Comment by knoxcard** [comment]
Ahhh the internet!!! Worldwide collaboration in mere minutes.
