### ISSUE TITLE
testnet.litecore.io websocket failure

### ISSUE THREAD

**Issue by ghost** [litecoin-project/litecore-node#7]
I was looking for a testnet litecore instance that I could use for testing some TREZOR related stuff.

I found testnet.litecore.io, but the web socket URL is failing:
`wss://testnet.litecore.io/socket.io/?EIO=3&transport=websocket`

The main net URL works:
`wss://insight.litecore.io/socket.io/?EIO=3&transport=websocket`

Would it be possible to get the testnet instance working like the main net one?

Sorry if this is the wrong place for this.

**Comment by losh11** [comment]
Weird, I'll take a look.

**Comment by ghost** [comment]
were you able to take a look?

**Comment by ghost** [comment]
is this the right place to ask about getting this fixed?

**Comment by LitecoinTim** [comment]
Hi @untrustbank , I have just enabled websocket support for the testnet node. Please try to connect once again. I've confirmed it works via [websocket.org](https://www.websocket.org/echo.html)

**Comment by ghost** [comment]
@LitecoinTim thanks, that looks like it works! i think i'll work on getting testnet litecoin support into trezor now. it should be easier now that there's a functioning testnet litecoin bitcore instance.

**Comment by sigdelbijay** [comment]
https://testnet.litecore.io/ isn't working although the main network(https://testnet.litecore.io/) works.

**Comment by ghost** [comment]
@sigdelbijay it's been up and down. i noticed it was down in april. when i mentioned it on my trezor pull request, it caused the pr to get closed, see https://github.com/trezor/trezor-common/pull/80#issuecomment-382382497.
if interested in getting trezor support, see also:
https://github.com/trezor/trezor-common/pull/80
https://github.com/trezor/trezor-mcu/pull/305

**Comment by ghost** [comment]
update: now if you use the latest trezor firmware and change the wallet settings in the trezor web wallet (https://wallet.trezor.io/) to use `https://testnet.litecore.io`, you can test trezor with the litecoin testnet! see screenshot for what to change:
![trezor-tltc-config](https://user-images.githubusercontent.com/28687328/42324824-4e330c9e-8032-11e8-8607-bbf019b64537.png)
